### ISSUE TITLE
KeyError: 'tracks'

### ISSUE THREAD

**Issue by Selshy** [TheComeUpCode/SpotifyGeneratePlaylist#13]
Get a KeyError from "tracks"
![Keyerror](https://user-images.githubusercontent.com/23476997/81345187-45580500-90b8-11ea-9086-4426b667467b.PNG)

**Comment by Livbojen** [comment]
Hi! This is most likely due to an expired spotify oauth token. Generate a new one and see if that fixes things for you :)

**Comment by Selshy** [comment]
Yeah, that seems to have been the problem, thanks!
