### ISSUE TITLE
Keyerror. Spotify wont open...

### ISSUE THREAD

**Issue by K-hackattack** [TheComeUpCode/SpotifyGeneratePlaylist#17]
[youtube] l0U7SxXHkPY: Downloading webpage
Traceback (most recent call last):
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Projectforexercising.py", line 151, in <module>
    cp.add_to_playlist()
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Projectforexercising.py", line 120, in add_to_playlist
    self.get_liked_videos()
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Projectforexercising.py", line 72, in get_liked_videos
    "spotify_url": self.get_spotify_url(song_name, artist)
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Projectforexercising.py", line 115, in get_spotify_url
    songs = response_json["tracks"]["items"]
KeyError: 'tracks'

**Comment by K-hackattack** [comment]
[youtube] l0U7SxXHkPY: Downloading webpage
[youtube] pwBFOuCrdr4: Downloading webpage
[youtube] xjmC4lSk-2U: Downloading webpage
[youtube] UuwtLvnHZ8c: Downloading webpage
Traceback (most recent call last):
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Sample code.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Sample code.py", line 120, in add_song_to_playlist
    self.get_liked_videos()
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Sample code.py", line 69, in get_liked_videos
    "spotify_uri": self.get_spotify_uri(song_name, artist)
  File "C:/Users/Kevin/PycharmProjects/PythonCode&Context/Sample code.py", line 113, in get_spotify_uri
    uri = songs[0]["uri"]
IndexError: list index out of range

**Comment by K-hackattack** [comment]
Now im getting this typo of IndexError

**Comment by harvestingmyhearth** [comment]
I have the same error, but still haven't managed to solve it. :(

**Comment by K-hackattack** [comment]
My Code is working now 🙌🏾😎
You gotta make sure that you got a new Token from Spotify. 
Make sure to take the whole code from the Spotify token website and enable authorization.

**Comment by Igorrubbo** [comment]
> My Code is working now 🙌🏾
> You gotta make sure that you got a new Token from Spotify.
> Make sure to take the whole code from the Spotify token website and enable authorization.

Just to add to that, since some people had trouble with it, you also have to make sure to select the boxes when getting a new token, as seen in the following image:

![Screenshot_1](https://user-images.githubusercontent.com/53878194/82827260-029e7700-9e85-11ea-8bf2-e96815d234ff.png)

Now that I think about it is pretty obvious that we should select it but I didn't and spent more time than I should stuck in this problem hehe

**Comment by harvestingmyhearth** [comment]
Thanks to both of you for the feedback! My error was actually different, I wrote the header with Content-Type following Authorization but I found that by reversing the order it worked. (I'm not using the code she provided, but I re-wrote everything playing around with a few things, just to be clear, it's not an error in her code)

**Comment by aditmodhvadia** [comment]
@TheComeUpCode We can close this now.

**Comment by CingedBrain** [comment]
Hi, 
I have tried all of the above suggestions and yet I I face the following error. Could someone offer any suggestions/solutions. You are greatly appreciated.
![Error](https://user-images.githubusercontent.com/72340279/95013543-86037c80-065e-11eb-81e0-43af63b1070a.PNG)

**Comment by K-hackattack** [comment]
Hey @CingedBrain Did you try to put a break into your code to check whether your code access Spotify ?

**Comment by CingedBrain** [comment]
hi @K-hackattack ,
Thanks for the reply. It was an issue with my secrets.py file, which i corrected. Now I am faced with the folowing issue. I also want it to be known that I am a complete newbie at coding.  
![Error 2](https://user-images.githubusercontent.com/72340279/95115472-29d65080-0763-11eb-95b2-d14296921892.PNG)

**Comment by K-hackattack** [comment]
@CingedBrain hey, I had the same problem it seems that the data that gets extracted by YouTube doesn't get into the Spotify app.

To solve this you should check if you authorized the Spotify token and see if Spotify runs when you run your code.

**Comment by CingedBrain** [comment]
@K-hackattack After checking spotify, it seems like it is creating the playlist each time I run the code but is unable to add any songs to the playlist. I have checked all the boxes for the token as someone above had suggested. I have also checked to make sure I liked a music video that is available on Spotify, I am still receiving the Error. I am posting the code below if it helps find a solution. Thanks in advance.

`import json
import os

import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
import requests
import youtube_dl

from exceptions import ResponseException
from secrets import spotify_token, spotify_user_id


class CreatePlaylist:
    def __init__(self):
        self.youtube_client = self.get_youtube_client()
        self.all_song_info = {}

    def get_youtube_client(self):
        """ Log Into Youtube, Copied from Youtube Data API """
        # Disable OAuthlib's HTTPS verification when running locally.
        # *DO NOT* leave this option enabled in production.
        os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

        api_service_name = "youtube"
        api_version = "v3"
        client_secrets_file = "client_secret.json"

        # Get credentials and create an API client
        scopes = ["https://www.googleapis.com/auth/youtube.readonly"]
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secret(
            client_secrets_file, scopes)
        credentials = flow.run_console()

        # from the Youtube DATA API
        youtube_client = googleapiclient.discovery.build(
            api_service_name, api_version, credentials=credentials)

        return youtube_client

    def get_liked_videos(self):
        """Grab Our Liked Videos & Create A Dictionary Of Important Song Information"""
        request = self.youtube_client.videos().list(
            part="snippet,contentDetails,statistics",
            myRating="like"
        )
        response = request.execute()

        # collect each video and get important information
        for item in response["items"]:
            video_title = item["snippet"]["title"]
            youtube_url = "https://www.youtube.com/watch?v={}".format(
                item["id"])

            # use youtube_dl to collect the song name & artist name
            video = youtube_dl.YoutubeDL({}).extract_info(
                youtube_url, download=False)
            song_name = video["track"]
            artist = video["artist"]

            if song_name is not None and artist is not None:
                # save all important info and skip any missing song and artist
                self.all_song_info[video_title] = {
                    "youtube_url": youtube_url,
                    "song_name": song_name,
                    "artist": artist,

                    # add the uri, easy to get song to put into playlist
                    "spotify_uri": self.get_spotify_uri(song_name, artist)

                }

    def create_playlist(self):
        """Create A New Playlist"""
        request_body = json.dumps({
            "name": "Youtube Liked Vids",
            "description": "All Liked Youtube Videos",
            "public": True
        })

        query = "https://api.spotify.com/v1/users/{}/playlists".format(
            spotify_user_id)
        response = requests.post(
            query,
            data=request_body,
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer {}".format(spotify_token)
            }
        )
        response_json = response.json()

        # playlist id
        return response_json["id"]

    def get_spotify_uri(self, song_name, artist):
        """Search For the Song"""
        query = "https://api.spotify.com/v1/search?query=track%3A{}+artist%3A{}&type=track&offset=0&limit=20".format(
            song_name,
            artist
        )
        response = requests.get(
            query,
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer {}".format(spotify_token)
            }
        )

        response_json = response.json()
        songs = response_json["tracks"]["items"]

        # only use the first song
        uri = songs[0]["uri"]

        return uri

    def add_song_to_playlist(self):
        """Add all liked songs into a new Spotify playlist"""
        # populate dictionary with our liked songs
        self.get_liked_videos()

        # collect all of uri
        uris = [info["spotify_uri"]
                for song, info in self.all_song_info.items()]

        # create a new playlist
        playlist_id = self.create_playlist()

        # add all songs into new playlist
        request_data = json.dumps(uris)

        query = "https://api.spotify.com/v1/playlists/{}/tracks".format(
            playlist_id)

        response = requests.post(
            query,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer {}".format(spotify_token)
            }
        )

        # check for valid response status
        if response.status_code != 200:
            raise ResponseException(response.status_code)

        response_json = response.json()
        return response_json


if __name__ == '__main__':
    cp = CreatePlaylist()
    cp.add_song_to_playlist()`

**Comment by K-hackattack** [comment]
@CingedBrain You should check somewhere in the code when it should add to the playlist, if it is getting the data from YouTube liked videos so you can check if it works.

**Comment by K-hackattack** [comment]
@CingedBrain could you Post what gets printed at the cmd at the line where Spotify should add songs into a playlist
