### ISSUE TITLE
how to get 0Auth from Spotify

### ISSUE THREAD

**Issue by zubiamansoor** [TheComeUpCode/SpotifyGeneratePlaylist#35]
I tried following the steps to get the spotify token and I select all the options for the scopes. But it redirects me to the page below, like a callback.
![Screen Shot 2020-12-02 at 10 24 58 AM](https://user-images.githubusercontent.com/55579981/100915049-bada5700-3488-11eb-9ba6-1816588965ef.png)

**Comment by cherellejohannes** [comment]
I didn't choose any of the options for scopes and it worked for me, maybe you could try that?

**Comment by aditmodhvadia** [comment]
@zubiamansoor It is a good practice to just select the scopes that are really required for the token, and hence it would be best to just select the read-private playlist and try it once again.

**Comment by qinnuoli** [comment]
I encountered the same issue when I tried to get an Oauth token from Spotify. I switched my browser from Safari to Chrome the other day and the problem solved itself! I don't know what browser you might be using. If you are also using Safari, try switching to Chrome? (Also, I only selected the scopes that are really required and left the others unselected, if that helps!)

**Comment by zubiamansoor** [comment]
Thanks, everyone for your help! Big shoutout to @qinnuoli, changing the browser from Safari to Chrome fixed it. Safari has given me grief for a lot of things before, should've known!
