### ISSUE TITLE
incorrect response_json

### ISSUE THREAD

**Issue by invalidexplorer** [TheComeUpCode/SpotifyGeneratePlaylist#5]
response_json isnt containing the list of songs returned, instead its containing the query.
E.g 
{'tracks': {'href': 'https://api.spotify.com/v1/search?query=track%3AYEAH+RIGHT+artist%3AJoji&type=track&offset=0&limit=20', 'items': [], 'limit': 20, 'next': None, 'offset': 0, 'previous': None, 'total': 0}}

**Comment by aishakubraali** [comment]
> response_json isnt containing the list of songs returned, instead its containing the query.
> E.g
> {'tracks': {'href': 'https://api.spotify.com/v1/search?query=track%3AYEAH+RIGHT+artist%3AJoji&type=track&offset=0&limit=20', 'items': [], 'limit': 20, 'next': None, 'offset': 0, 'previous': None, 'total': 0}}

Sorry where is this, and what should be written instead?

**Comment by invalidexplorer** [comment]
> > response_json isnt containing the list of songs returned, instead its containing the query.
> > E.g
> > {'tracks': {'href': 'https://api.spotify.com/v1/search?query=track%3AYEAH+RIGHT+artist%3AJoji&type=track&offset=0&limit=20', 'items': [], 'limit': 20, 'next': None, 'offset': 0, 'previous': None, 'total': 0}}
> 
> Sorry where is this, and what should be written instead?

I have fixed the problem in my fork.

**Comment by aditmodhvadia** [comment]
@invalidexplorer Please create a pull request for your work if you are fine with it. It will help others as well.

**Comment by invalidexplorer** [comment]
> @invalidexplorer Please create a pull request for your work if you are fine with it. It will help others as well.

Done!
