### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR

### ISSUE THREAD

**Issue by ryosukenakagiri** [TheComeUpCode/SpotifyGeneratePlaylist#8]
I got below error. Please help.
　
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

**Comment by TheComeUpCode** [comment]
This might provide more information: https://github.com/ytdl-org/youtube-dl/issues/15417

Seems to be an issue on youtube DL's end

**Comment by ryosukenakagiri** [comment]
Thanks for reply.

Is there any solution for this error?

**Comment by ryosukenakagiri** [comment]
I solved the problem! I tried below command which mentioned in https://github.com/ytdl-org/youtube-dl/issues/4816:

pip3 install certifi
Then
/Applications/Python\ 3.7/Install\ Certificates.command
